# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WeBo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeBo
pod 'SVProgressHUD'
pod 'FDFullscreenPopGesture'
pod 'MJRefresh'
pod 'SnapKit', '~> 3.0.2'
pod 'AFNetworking', '~> 3.1.0'

end
